name: lint / check

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run secretlint
        shell: bash
        run: pnpm dlx @secretlint/quick-start $(git ls-files)
      - name: Run check
        run: pnpm check
      - name: Run lint
        run: pnpm lint
      - name: publish to pkg-pr-now
        run: pnpm dlx pkg-pr-new publish
